### ISSUE TITLE
skpm link not working

### ISSUE THREAD

**Issue by kevincannon** [sketch-pm/skpm#23]
The **skpm link** command isn't working at all for me. Here's the error code.
Any ideas?

Here's the full error message:

```
skpm link max-character-count.sketchplugin/
error Error while reading the package.json file
{ Error: Cannot find module '/Users/kevin.cannon/Repositories/SketchPlugins/max-character-count/max-character-count.sketchplugin/package.json'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/skpm/lib/skpm-link.js:55:17)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' }

```

**Comment by mathieudutour** [comment]
don't point it to the .sketchplugin, just the repo. So if you are already in your repo `skpm link .` or `skpm link` directly

**Comment by kevincannon** [comment]
Boom!

That worked - thanks very much!

**Comment by mathieudutour** [comment]
if you feel like it, you can create a PR to check if the path given contains `.sketchplugin`. Then it's probably the same mistake as yours and we could give a nicer error message
