### ISSUE TITLE
Local imports not working

### ISSUE THREAD

**Issue by jongold** [sketch-pm/skpm#24]
I think there's something up with the rollup config - this doesn't fail with a fresh rollup project. made a vanilla skpm project - it's not related to react-sketchapp.

`skpm init` & then…
```js
/* my-command.js */
import foo from './foo';

export default function (context) {
  context.document.showMessage(foo())
}

/* foo.js */
const foo = () => 'bar';

export default foo;
```

```
λ yarn build
yarn build v0.21.3
$ skpm build
[1/2] 🖨  Copied src/manifest.json in 75ms
error Error while building ./my-command.js
{ Error: 'default' is not exported by src/foo.js
    at error (/usr/local/lib/node_modules/skpm/node_modules/rollup/dist/rollup.js:170:12)
    at Module.error$1 [as error] (/usr/local/lib/node_modules/skpm/node_modules/rollup/dist/rollup.js:8007:2)
    at Module.trace (/usr/local/lib/node_modules/skpm/node_modules/rollup/dist/rollup.js:8106:9)
    at ModuleScope.findDeclaration (/usr/local/lib/node_modules/skpm/node_modules/rollup/dist/rollup.js:7691:22)
    at Scope.findDeclaration (/usr/local/lib/node_modules/skpm/node_modules/rollup/dist/rollup.js:5497:39)
    at Node.bind (/usr/local/lib/node_modules/skpm/node_modules/rollup/dist/rollup.js:6022:28)
    at /usr/local/lib/node_modules/skpm/node_modules/rollup/dist/rollup.js:5291:50
    at Node.eachChild (/usr/local/lib/node_modules/skpm/node_modules/rollup/dist/rollup.js:5305:19)
    at Node.bind (/usr/local/lib/node_modules/skpm/node_modules/rollup/dist/rollup.js:5291:7)
    at Node.bind (/usr/local/lib/node_modules/skpm/node_modules/rollup/dist/rollup.js:6040:23)
  code: 'MISSING_EXPORT',
  url: 'https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module',
  pos: 7,
  loc:
   { file: '/Users/jon_gold/code/jongold/skpm-imports/src/my-command.js',
     line: 1,
     column: 7 },
  frame: '1: import foo from \'./foo\';\n          ^\n2: \n3: module.exports.__skpm_export__ = function (context) {' }
error Command failed with exit code 1.
```

Attaching the project folder, and a simple rollup example that shows that it should work :)
[skpm-imports.zip](https://github.com/sketch-pm/skpm/files/891705/skpm-imports.zip)
[rollup-common-js-defaults.zip](https://github.com/sketch-pm/skpm/files/891708/rollup-common-js-defaults.zip)

**Comment by mathieudutour** [comment]
Hum that's really weird, it's failing in this simple example but it's working in https://github.com/mathieudutour/git-sketch-plugin.

Anyhow, I fixed it in `skpm@0.7.1`
